//Manager

### 获得一个正在进行中的比赛
GET http://{{hostname}}/manager/system/runningCompetition


### 创建一个比赛，如果成功会被设置为alive

POST http://{{hostname}}/manager/competition
Content-Type: application/json

{
  "startTime": "2021-04-03 22:07:21",
  "endTime": "2021-04-30 12:00:00",
  "score": 100
}

### 将所有比赛置为停止

DELETE http://{{hostname}}/manager/system/competition


//Team

### 增
POST http://{{hostname}}/manager/team
Content-Type: application/json

{
  "name": "test2",
  "logo": ""
}

### 删
DELETE http://{{hostname}}/manager/team?id=3

### 改
PUT http://{{hostname}}/manager/team
Content-Type: application/json

{
  "id": 2,
  "name": "test2",
  "logo": ""
}

### 查
GET http://{{hostname}}/manager/teams



//Pod

### 清理资源
GET http://{{hostname}}/manager/clear

### 列出服务入口
GET http://{{hostname}}/manager/services



//Flag

### 提交flag
POST http://{{hostname}}/flag
Content-Type: application/json

{"flag": "test"}