spring:
  datasource:
    druid:
      url: jdbc:mysql://121.36.230.118:3306/k8s?useUnicode=true&characterEncoding=utf8&useTimezone=true&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&useSSL=true
      username: root
      password: justmiss

server:
  port: 7070
