spring:
  datasource:
    druid:
      url: jdbc:mysql://121.36.230.118:3306/k8s?useUnicode=true&characterEncoding=utf8&useTimezone=true&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&useSSL=true
      username: root
      password: justmiss

server:
  port: 7070


k8s-awd:
  master-url: https://121.36.230.118:6443
  ca-cert-file: ca.crt
  client-cert-file: apiserver-kubelet-client.crt
  client-key-file: apiserver-kubelet-client.key

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    banner: false